### ISSUE TITLE
Parkour Mode - Initial State

### ISSUE THREAD

**Issue by SerhanTRGL** [CNG491ERG/AIBERG#43]
• Upon loading the game scene, the state machine inside the scene will be in the “Initial State”. This state will be used to kick-start the game. Upon completion of this state (it can last for an arbitrary amount of time, let’s say 2.5 seconds), time and score counters will start to count. An example of what is meant can be seen in the gif below.
![image](https://github.com/CNG491ERG/AIBERG/assets/35522745/49478477-1c21-4318-b549-95d6fc9984e5)

**Comment by krizantemum** [comment]
I don't understand what time counter means and does in this context @SerhanTRGL

**Comment by SerhanTRGL** [comment]
> I don't understand what time counter means and does in this context @SerhanTRGL 

It's just a UI element, but, in your state machine (not in the states but state machine itself), have a variable that holds a step counter variable and make it so that it is only incremented when the below variable is set to true.
Also have a boolean variable that is named countStep. This should be set to negative in initial state and death state
We can derive the time from that so you don't have to worry about it.
