### ISSUE TITLE
Parkour Mode - Parkour State

### ISSUE THREAD

**Issue by SerhanTRGL** [CNG491ERG/AIBERG#44]
- After initial state is complete, the game will switch to parkour state. 
- In this state, the player will try to avoid some obstacles coming towards them. If the player hits any projectile, they will die immediately.
- There is an easy way to accomplish this effect, which is by giving a “DamagingProjectile” component to all obstacles, and setting their damage to a very high number. 
- Upon death, the game can switch to a death state in which there will be a small animation depicting the death of the player. 
- The parkour state will last for an arbitrary amount of time (120 seconds currently), and after that time the state machine will switch to “parkour-to-boss transition state”. 
- Boss game object will be disabled in this state. 
- We also need to keep track of how many times the player has been in this state for the duration of their playthrough. Due to the nature of an endless runner game, we will need to speed up the game eventually, and we can do so by utilizing the number of times the player comes to this state.

**Comment by krizantemum** [comment]
Floating point problem later
