### ISSUE TITLE
Parkour Mode - Boss State

### ISSUE THREAD

**Issue by SerhanTRGL** [CNG491ERG/AIBERG#47]
- In the boss state, the boss will come on screen.
- This will be achieved by activating the boss game object off-screen, moving it on screen, to their designated coordinate, and then activating all its components. We will probably need to create a new function to control this disable/enable behavior. 
- There are three things that we need to consider. 
- First one is, we need to keep track of how many times the player comes into this state, because this way, we can make the boss a little more stronger (in terms of damage) every time the player comes to this state.
- Second thing is, the player might die during this state, and in this case, we must switch to death state.
- Third thing is on killing the boss, then we must reset the boss’s health every time its killed, reset its cooldowns, and make it a little stronger. This way, we can keep upping the challenge, without adding any difficulty levels. Our boss already supports this with its “Enragement” stat. 
- Killing the boss will switch the state machine to boss-to-parkour-transition state

**Comment by krizantemum** [comment]
I think killing the boss/player makes most sense regarding as state ending parameter. Do you agree? @SerhanTRGL

**Comment by SerhanTRGL** [comment]
> I think killing the boss/player makes most sense regarding as state ending parameter. Do you agree? @SerhanTRGL

That would simplify the logic quite a bit, so yeah let's go with that. I'll edit the issue accordingly.
